'use client';

/**
 * Pre-Departure Brief Composer (B2B advisor)
 * Phase 4 §6 shape: summary + logistics + advisor_notes + auto_generated.
 * Split view: composer on the left, UHNI-facing preview on the right.
 * advisorNotes is INTERNAL and must never render in the UHNI preview.
 */

import { useEffect, useState } from 'react';
import Image from 'next/image';
import { toast } from 'sonner';
import { cn } from '@/lib/utils/cn';
import { AlertTriangle, Wand2, Send, Loader2, Lock } from 'lucide-react';
import { useServices } from '@/lib/hooks/useServices';
import type { PreDepartureBrief as Brief } from '@/lib/types/entities';
import { logger } from '@/lib/utils/logger';
import { Modal } from '@/components/shared/Modal/Modal';

interface PreDepartureBriefProps {
  journeyId: string;
  clientName: string;
  journeyTitle: string;
  initialBrief?: Brief | null;
  onSaved?: () => void;
}

interface LogisticsDraft {
  transfer: string;
  duration: string;
  contact: string;
}

const EMPTY_LOGISTICS: LogisticsDraft = { transfer: '', duration: '', contact: '' };

const AGI_TEMPLATE = {
  summary:
    'Your experience begins with complete discretion. A dedicated host will greet you privately upon arrival, and every subsequent moment has been pre-coordinated on your behalf — simply arrive as planned.',
  logistics: {
    transfer: 'Private transfer arranged from arrival point',
    duration: '45 minutes',
    contact: 'Your Élan concierge — available 24/7 through your secure channel',
  },
  advisor_notes:
    'Client prefers minimal digital communication during travel. All updates via secure channel only.',
};

function logisticsFromBrief(l: Brief['logistics']): LogisticsDraft {
  if (!l || typeof l !== 'object') return { ...EMPTY_LOGISTICS };
  return {
    transfer: typeof l.transfer === 'string' ? l.transfer : '',
    duration: typeof l.duration === 'string' ? l.duration : '',
    contact: typeof l.contact === 'string' ? l.contact : '',
  };
}

function logisticsToPayload(l: LogisticsDraft): Record<string, unknown> | null {
  const entries = Object.entries(l).filter(([, v]) => v.trim().length > 0);
  if (entries.length === 0) return null;
  return Object.fromEntries(entries);
}

export function PreDepartureBrief({
  journeyId,
  clientName,
  journeyTitle,
  initialBrief,
  onSaved,
}: PreDepartureBriefProps) {
  const services = useServices();
  const [summary, setSummary] = useState(initialBrief?.summary ?? '');
  const [logistics, setLogistics] = useState<LogisticsDraft>(
    logisticsFromBrief(initialBrief?.logistics)
  );
  const [advisorNotes, setAdvisorNotes] = useState(initialBrief?.advisorNotes ?? '');
  const [autoGenerated, setAutoGenerated] = useState(
    initialBrief?.autoGenerated ?? false
  );
  const [sent, setSent] = useState(Boolean(initialBrief?.createdAt));
  const [sending, setSending] = useState(false);
  // Track whether the loaded brief was already sent at least once. Used to
  // show a re-send confirmation modal — backend re-emails on every save
  // (FRONTEND_EMAIL_INTEGRATION §4.5).
  const [hasBeenSent, setHasBeenSent] = useState(Boolean(initialBrief?.createdAt));
  const [confirmResendOpen, setConfirmResendOpen] = useState(false);

  useEffect(() => {
    if (initialBrief) {
      setSummary(initialBrief.summary ?? '');
      setLogistics(logisticsFromBrief(initialBrief.logistics));
      setAdvisorNotes(initialBrief.advisorNotes ?? '');
      setAutoGenerated(initialBrief.autoGenerated ?? false);
      const wasSent = Boolean(initialBrief.createdAt);
      setSent(wasSent);
      setHasBeenSent(wasSent);
    }
  }, [initialBrief]);

  const applyTemplate = () => {
    logger.action('Brief', 'apply AGI template', { journeyId });
    setSummary(AGI_TEMPLATE.summary);
    setLogistics({ ...AGI_TEMPLATE.logistics });
    setAdvisorNotes(AGI_TEMPLATE.advisor_notes);
    setAutoGenerated(true);
  };

  const performSend = async () => {
    setSending(true);
    logger.action('Brief', 'send pre-departure', {
      journeyId,
      autoGenerated,
      hasLogistics: Object.values(logistics).some((v) => v.trim().length > 0),
      isResend: hasBeenSent,
    });
    try {
      await services.journey.setPreDepartureBrief(journeyId, {
        summary,
        logistics: logisticsToPayload(logistics),
        advisorNotes: advisorNotes || undefined,
        autoGenerated,
      });
      setSent(true);
      setHasBeenSent(true);
      // FRONTEND_EMAIL_INTEGRATION §4.5 — backend emails UHNI + Spouse/Heir + RM.
      toast.success('Pre-departure briefing saved. Sent to client and team.');
      onSaved?.();
    } catch (err) {
      logger.error('Brief', 'send failed', err, { journeyId });
      toast.error('Unable to send brief. Please try again.');
    } finally {
      setSending(false);
    }
  };

  const handleSend = async () => {
    if (!summary.trim()) {
      toast.error('Summary is required — this is what the client will see.');
      return;
    }
    if (hasBeenSent) {
      // Backend silently re-emails on every save — confirm before re-sending.
      setConfirmResendOpen(true);
      return;
    }
    await performSend();
  };

  const handleConfirmResend = async () => {
    setConfirmResendOpen(false);
    await performSend();
  };

  const hasContent = summary.trim().length > 0;

  return (
    <div className="bg-white border border-slate-200 rounded-xl overflow-hidden">
      <div className="px-6 py-4 border-b border-slate-200 flex items-center justify-between bg-slate-50">
        <div>
          <p className="font-sans text-sm font-medium text-slate-800">
            Pre-Departure Brief
          </p>
          <p className="text-slate-500 text-xs font-sans">
            For {clientName} — {journeyTitle}
          </p>
        </div>
        <button
          onClick={applyTemplate}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-blue-50 text-blue-600 border border-blue-200 font-sans text-xs font-medium hover:bg-blue-100 transition-colors"
        >
          <Wand2 size={12} />
          Use AGI Template
        </button>
      </div>

      {sent ? (
        <div className="px-6 py-10 text-center">
          <p className="text-emerald-600 font-sans font-medium mb-1">
            Brief sent successfully.
          </p>
          <p className="text-slate-400 text-sm font-sans mb-4">
            Client has been notified through their secure channel.
          </p>
          <button
            onClick={() => setSent(false)}
            className="text-blue-600 text-xs font-sans hover:underline"
          >
            Edit &amp; resend
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 divide-y lg:divide-y-0 lg:divide-x divide-slate-200">
          {/* ── Composer ────────────────────────────────────────── */}
          <div className="p-6 space-y-4">
            <div>
              <label className="block text-xs font-sans font-medium text-slate-500 uppercase tracking-wider mb-1.5">
                Summary <span className="text-rose-500 normal-case tracking-normal">*</span>
              </label>
              <textarea
                value={summary}
                onChange={(e) => setSummary(e.target.value)}
                rows={4}
                placeholder="Calm summary the UHNI will see before their journey begins..."
                className="w-full px-3 py-2 rounded-lg border border-slate-200 bg-slate-50 text-slate-800 text-sm font-sans placeholder-slate-400 resize-none focus:outline-none focus:border-blue-300"
              />
            </div>

            <div>
              <p className="text-xs font-sans font-medium text-slate-500 uppercase tracking-wider mb-2">
                Logistics <span className="text-slate-300 normal-case tracking-normal">(optional)</span>
              </p>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <input
                  value={logistics.transfer}
                  onChange={(e) => setLogistics({ ...logistics, transfer: e.target.value })}
                  placeholder="Transfer"
                  className="px-3 py-2 rounded-lg border border-slate-200 bg-slate-50 text-slate-800 text-sm font-sans placeholder-slate-400 focus:outline-none focus:border-blue-300"
                />
                <input
                  value={logistics.duration}
                  onChange={(e) => setLogistics({ ...logistics, duration: e.target.value })}
                  placeholder="Duration"
                  className="px-3 py-2 rounded-lg border border-slate-200 bg-slate-50 text-slate-800 text-sm font-sans placeholder-slate-400 focus:outline-none focus:border-blue-300"
                />
                <input
                  value={logistics.contact}
                  onChange={(e) => setLogistics({ ...logistics, contact: e.target.value })}
                  placeholder="Contact"
                  className="px-3 py-2 rounded-lg border border-slate-200 bg-slate-50 text-slate-800 text-sm font-sans placeholder-slate-400 focus:outline-none focus:border-blue-300"
                />
              </div>
            </div>

            <div>
              <label className="flex items-center gap-1.5 text-xs font-sans font-medium text-slate-500 uppercase tracking-wider mb-1.5">
                Advisor Notes
                <span className="inline-flex items-center gap-1 text-amber-600 normal-case tracking-normal">
                  <Lock size={10} />
                  internal only
                </span>
              </label>
              <textarea
                value={advisorNotes}
                onChange={(e) => setAdvisorNotes(e.target.value)}
                rows={2}
                placeholder="Never shown to the client..."
                className="w-full px-3 py-2 rounded-lg border border-amber-200 bg-amber-50/40 text-slate-800 text-sm font-sans placeholder-amber-300 resize-none focus:outline-none focus:border-amber-400"
              />
            </div>

            <label className="flex items-center gap-2 text-xs font-sans text-slate-500">
              <input
                type="checkbox"
                checked={autoGenerated}
                onChange={(e) => setAutoGenerated(e.target.checked)}
                className="rounded border-slate-300"
              />
              Mark as AI-generated
            </label>

            <button
              onClick={handleSend}
              disabled={!hasContent || sending}
              className={cn(
                'w-full flex items-center justify-center gap-2 py-2.5 rounded-lg font-sans text-sm font-medium transition-all',
                hasContent && !sending
                  ? 'bg-blue-600 text-white hover:bg-blue-700'
                  : 'bg-slate-100 text-slate-400 cursor-not-allowed'
              )}
            >
              {sending ? <Loader2 size={14} className="animate-spin" /> : <Send size={14} />}
              {sending ? 'Sending…' : 'Send to Client'}
            </button>
          </div>

          {/* Re-send confirmation — FRONTEND_EMAIL_INTEGRATION §4.5 */}
          <Modal
            open={confirmResendOpen}
            onOpenChange={setConfirmResendOpen}
            title="Re-send the pre-departure briefing?"
            description="The client and assigned team have already received this brief. Saving will re-send the email to all of them."
          >
            <div className="space-y-4">
              <div className="flex items-start gap-3 px-3 py-2.5 bg-amber-50 border border-amber-200 rounded-md text-xs font-sans text-amber-800">
                <AlertTriangle size={14} className="flex-shrink-0 mt-0.5" />
                <span>
                  Recipients: UHNI + linked Spouse/Heir + assigned RM. Backend
                  re-sends silently on every save.
                </span>
              </div>
              <div className="flex justify-end gap-3">
                <button
                  type="button"
                  onClick={() => setConfirmResendOpen(false)}
                  className="px-4 py-2 border border-slate-300 text-slate-700 text-sm font-sans rounded-md hover:bg-slate-50 transition-colors"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={handleConfirmResend}
                  className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white text-sm font-sans rounded-md hover:bg-blue-700 transition-colors"
                >
                  <Send size={14} />
                  Re-send brief
                </button>
              </div>
            </div>
          </Modal>

          {/* ── Client-facing preview (NO advisor_notes) ───────────── */}
          <div className="p-6 bg-sand-50">
            <p className="text-xs font-sans font-medium text-slate-400 uppercase tracking-wider mb-4">
              Client Preview
            </p>
            {hasContent ? (
              <div className="bg-white rounded-xl border border-sand-200 p-5">
                <Image
                  src="/Logo/elan-glimmora.png"
                  alt="Élan Glimmora"
                  width={100}
                  height={28}
                  className="h-6 w-auto mb-1"
                />
                <h4 className="font-serif text-lg text-rose-900 mb-4">
                  Your Experience Brief
                </h4>
                <p className="text-sand-700 font-sans text-sm leading-relaxed whitespace-pre-wrap">
                  {summary}
                </p>

                {(logistics.transfer || logistics.duration || logistics.contact) && (
                  <div className="mt-4 pt-3 border-t border-sand-100 space-y-2">
                    {logistics.transfer && (
                      <div>
                        <p className="text-[10px] text-sand-400 uppercase tracking-wider font-sans mb-0.5">
                          Transfer
                        </p>
                        <p className="text-sand-700 font-sans text-xs">{logistics.transfer}</p>
                      </div>
                    )}
                    {logistics.duration && (
                      <div>
                        <p className="text-[10px] text-sand-400 uppercase tracking-wider font-sans mb-0.5">
                          Duration
                        </p>
                        <p className="text-sand-700 font-sans text-xs">{logistics.duration}</p>
                      </div>
                    )}
                    {logistics.contact && (
                      <div>
                        <p className="text-[10px] text-sand-400 uppercase tracking-wider font-sans mb-0.5">
                          Contact
                        </p>
                        <p className="text-sand-700 font-sans text-xs">{logistics.contact}</p>
                      </div>
                    )}
                  </div>
                )}
              </div>
            ) : (
              <div className="bg-white rounded-xl border border-sand-200 p-5 text-center">
                <p className="text-sand-400 font-sans text-sm">
                  Begin composing or use the AGI template to see the client preview.
                </p>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
