/**
 * Real API Journey Service
 * Implements IJourneyService against the Elan Glimmora backend API
 */

import type {
  Journey,
  JourneyVersion,
  JourneyFeedback,
  PreDepartureBrief,
  TravelMonitor,
  JourneyCategory,
  JourneyStatus,
  DiscretionLevel,
  CreateJourneyInput,
  DomainContext,
} from '@/lib/types';
import type { IJourneyService } from '../interfaces/IJourneyService';
import { api } from './client';
import { logger } from '@/lib/utils/logger';

// ── Backend shapes (snake_case) ──────────────────────────────────────────────

interface ApiJourney {
  id: string;
  user_id: string;
  institution_id?: string | null;
  assigned_rm?: string | null;
  title: string;
  narrative: string;
  category: JourneyCategory;
  status: JourneyStatus;
  versions?: ApiJourneyVersion[] | null;
  current_version_id?: string | null;
  risk_summary?: string | null;
  discretion_level?: DiscretionLevel | null;
  is_invisible: boolean;
  emotional_objective?: string | null;
  strategic_reasoning?: string | null;
  package_id?: string | null;
  pre_departure_brief?: ApiPreDepartureBrief | null;
  /** AGI Intelligence Layer §2 — 'ai' for OpenAI-generated narratives, 'template' for fallback. */
  source?: 'ai' | 'template' | null;
  created_at: string;
  updated_at: string;
}

interface ApiPreDepartureBrief {
  id?: string;
  journey_id?: string;
  summary: string;
  logistics?: Record<string, unknown> | null;
  advisor_notes?: string | null;
  auto_generated?: boolean;
  created_by?: string | null;
  created_at?: string;
}

interface ApiJourneyFeedback {
  id?: string;
  journey_id: string;
  user_id?: string;
  mood: number;
  reflection?: string | null;
  emotional_tags?: string[] | null;
  created_at?: string;
}

interface ApiTravelMonitorStatusCard {
  status: string;
  details: string;
}

interface ApiTravelMonitor {
  journey_id: string;
  status: string;
  title: string;
  discretion_level?: string | null;
  assigned_rm?: string | null;
  package?: {
    package_id: string;
    package_name: string;
    duration: string;
    region: string;
  } | null;
  pre_departure_brief?: ApiPreDepartureBrief | null;
  operational_status: {
    flight: ApiTravelMonitorStatusCard;
    accommodation: ApiTravelMonitorStatusCard;
    ground_transfer: ApiTravelMonitorStatusCard;
    security: ApiTravelMonitorStatusCard;
  };
  last_updated: string;
}

interface ApiJourneyVersion {
  id: string;
  journey_id: string;
  version_number: number;
  title: string;
  narrative: string;
  status: JourneyStatus;
  approved_by?: string | null;
  rejected_by?: string | null;
  rejection_reason?: string | null;
  modified_by: string;
  created_at: string;
}

// ── Mappers ──────────────────────────────────────────────────────────────────

function toJourneyVersion(raw: ApiJourneyVersion): JourneyVersion {
  return {
    id: raw.id,
    journeyId: raw.journey_id,
    versionNumber: raw.version_number,
    title: raw.title,
    narrative: raw.narrative,
    status: raw.status,
    approvedBy: raw.approved_by || undefined,
    rejectedBy: raw.rejected_by || undefined,
    rejectionReason: raw.rejection_reason || undefined,
    modifiedBy: raw.modified_by,
    createdAt: raw.created_at,
  };
}

function toJourney(raw: ApiJourney, sourceOverride?: 'ai' | 'template'): Journey {
  return {
    id: raw.id,
    userId: raw.user_id,
    institutionId: raw.institution_id || undefined,
    assignedRM: raw.assigned_rm || undefined,
    title: raw.title,
    narrative: raw.narrative,
    category: raw.category,
    status: raw.status,
    versions: (raw.versions || []).map(toJourneyVersion),
    currentVersionId: raw.current_version_id || '',
    riskSummary: raw.risk_summary || undefined,
    discretionLevel: (raw.discretion_level as DiscretionLevel) || undefined,
    isInvisible: raw.is_invisible,
    emotionalObjective: raw.emotional_objective || undefined,
    strategicReasoning: raw.strategic_reasoning || undefined,
    packageId: raw.package_id ?? null,
    preDepartureBrief: raw.pre_departure_brief ? toPreDepartureBrief(raw.pre_departure_brief) : null,
    source: sourceOverride ?? raw.source ?? undefined,
    createdAt: raw.created_at,
    updatedAt: raw.updated_at,
  };
}

function toPreDepartureBrief(raw: ApiPreDepartureBrief): PreDepartureBrief {
  return {
    id: raw.id ?? '',
    journeyId: raw.journey_id ?? '',
    summary: raw.summary,
    logistics: raw.logistics ?? null,
    advisorNotes: raw.advisor_notes || undefined,
    autoGenerated: raw.auto_generated ?? false,
    createdBy: raw.created_by || undefined,
    createdAt: raw.created_at ?? new Date().toISOString(),
  };
}

/**
 * Body for POST /api/journeys/{id}/pre-departure per Phase 4 §6.
 * Advisors POST the composer form; only `summary` is required.
 */
function toApiPreDepartureBody(
  brief: Pick<
    PreDepartureBrief,
    'summary' | 'logistics' | 'advisorNotes' | 'autoGenerated'
  >
): Record<string, unknown> {
  return {
    summary: brief.summary,
    logistics: brief.logistics ?? null,
    advisor_notes: brief.advisorNotes ?? null,
    auto_generated: brief.autoGenerated ?? false,
  };
}

function toFeedback(raw: ApiJourneyFeedback): JourneyFeedback {
  return {
    id: raw.id ?? '',
    journeyId: raw.journey_id,
    userId: raw.user_id ?? '',
    mood: raw.mood,
    reflection: raw.reflection || undefined,
    emotionalTags: raw.emotional_tags ?? [],
    createdAt: raw.created_at ?? new Date().toISOString(),
  };
}

function toStatusCard(raw: ApiTravelMonitorStatusCard | undefined) {
  return {
    status: raw?.status ?? 'Unknown',
    details: raw?.details ?? '',
  };
}

function toMonitor(raw: ApiTravelMonitor): TravelMonitor {
  const ops = raw.operational_status ?? ({} as ApiTravelMonitor['operational_status']);
  return {
    journeyId: raw.journey_id,
    status: raw.status,
    title: raw.title,
    discretionLevel: raw.discretion_level ?? null,
    assignedRM: raw.assigned_rm ?? null,
    package: raw.package
      ? {
          packageId: raw.package.package_id,
          packageName: raw.package.package_name,
          duration: raw.package.duration,
          region: raw.package.region,
        }
      : null,
    preDepartureBrief: raw.pre_departure_brief
      ? toPreDepartureBrief(raw.pre_departure_brief)
      : null,
    operationalStatus: {
      flight: toStatusCard(ops.flight),
      accommodation: toStatusCard(ops.accommodation),
      groundTransfer: toStatusCard(ops.ground_transfer),
      security: toStatusCard(ops.security),
    },
    lastUpdated: raw.last_updated ?? new Date().toISOString(),
  };
}

/** Convert camelCase frontend fields to snake_case API body */
function toApiCreateBody(data: CreateJourneyInput) {
  return {
    user_id: data.userId,
    title: data.title,
    narrative: data.narrative,
    category: data.category,
  };
}

function toApiUpdateBody(data: Partial<Journey>) {
  const body: Record<string, unknown> = {};
  if (data.title !== undefined) body.title = data.title;
  if (data.narrative !== undefined) body.narrative = data.narrative;
  if (data.category !== undefined) body.category = data.category;
  if (data.assignedRM !== undefined) body.assigned_rm = data.assignedRM;
  if (data.riskSummary !== undefined) body.risk_summary = data.riskSummary;
  if (data.discretionLevel !== undefined) body.discretion_level = data.discretionLevel;
  if (data.isInvisible !== undefined) body.is_invisible = data.isInvisible;
  if (data.emotionalObjective !== undefined) body.emotional_objective = data.emotionalObjective;
  if (data.strategicReasoning !== undefined) body.strategic_reasoning = data.strategicReasoning;
  if (data.packageId !== undefined) body.package_id = data.packageId;
  return body;
}

// ── Service ──────────────────────────────────────────────────────────────────

export class ApiJourneyService implements IJourneyService {
  async getJourneys(userId: string, _context: DomainContext): Promise<Journey[]> {
    const raw = await api.get<ApiJourney[]>(`/api/journeys?userId=${encodeURIComponent(userId)}`);
    return raw.map((j) => toJourney(j));
  }

  async getJourneyById(id: string): Promise<Journey | null> {
    try {
      const raw = await api.get<ApiJourney>(`/api/journeys/${id}`);
      return toJourney(raw);
    } catch {
      return null;
    }
  }

  async createJourney(data: CreateJourneyInput): Promise<Journey> {
    const raw = await api.post<ApiJourney>('/api/journeys', toApiCreateBody(data));
    return toJourney(raw);
  }

  async updateJourney(id: string, data: Partial<Journey>): Promise<Journey> {
    const raw = await api.patch<ApiJourney>(`/api/journeys/${id}`, toApiUpdateBody(data));
    return toJourney(raw);
  }

  async deleteJourney(id: string): Promise<boolean> {
    await api.delete(`/api/journeys/${id}`);
    return true;
  }

  async getJourneyVersions(journeyId: string): Promise<JourneyVersion[]> {
    const raw = await api.get<ApiJourneyVersion[]>(`/api/journeys/${journeyId}/versions`);
    return raw.map(toJourneyVersion);
  }

  async createJourneyVersion(
    journeyId: string,
    data: Partial<JourneyVersion>
  ): Promise<JourneyVersion> {
    const body: Record<string, unknown> = {};
    if (data.title !== undefined) body.title = data.title;
    if (data.narrative !== undefined) body.narrative = data.narrative;
    if (data.status !== undefined) body.status = data.status;
    if (data.modifiedBy !== undefined) body.modified_by = data.modifiedBy;

    const raw = await api.post<ApiJourneyVersion>(
      `/api/journeys/${journeyId}/versions`,
      body
    );
    return toJourneyVersion(raw);
  }

  async transitionJourney(
    journeyId: string,
    event: string,
    rejectionReason?: string
  ): Promise<Journey> {
    const body: Record<string, unknown> = { event };
    if (rejectionReason) body.rejection_reason = rejectionReason;

    const raw = await api.post<ApiJourney>(
      `/api/journeys/${journeyId}/transition`,
      body
    );
    return toJourney(raw);
  }

  async setPreDepartureBrief(
    journeyId: string,
    brief: Pick<
      PreDepartureBrief,
      'summary' | 'logistics' | 'advisorNotes' | 'autoGenerated'
    >
  ): Promise<Journey> {
    logger.info('Journey', 'setPreDepartureBrief', {
      journeyId,
      hasLogistics: !!brief.logistics,
      autoGenerated: !!brief.autoGenerated,
    });
    const raw = await api.post<ApiJourney>(
      `/api/journeys/${journeyId}/pre-departure`,
      toApiPreDepartureBody(brief)
    );
    return toJourney(raw);
  }

  async getMonitor(journeyId: string): Promise<TravelMonitor> {
    logger.info('Journey', 'getMonitor', { journeyId });
    const raw = await api.get<ApiTravelMonitor>(`/api/journeys/${journeyId}/monitor`);
    return toMonitor(raw);
  }

  async submitFeedback(
    journeyId: string,
    feedback: { mood: number; reflection?: string; emotional_tags?: string[] }
  ): Promise<JourneyFeedback> {
    logger.info('Journey', 'submitFeedback', {
      journeyId,
      mood: feedback.mood,
      tagCount: feedback.emotional_tags?.length ?? 0,
    });
    const raw = await api.post<ApiJourneyFeedback>(
      `/api/journeys/${journeyId}/feedback`,
      {
        mood: feedback.mood,
        reflection: feedback.reflection ?? null,
        emotional_tags: feedback.emotional_tags ?? [],
      }
    );
    return toFeedback(raw);
  }

  async getFeedback(journeyId: string): Promise<JourneyFeedback | null> {
    logger.info('Journey', 'getFeedback', { journeyId });
    try {
      const raw = await api.get<ApiJourneyFeedback>(`/api/journeys/${journeyId}/feedback`);
      return toFeedback(raw);
    } catch (err) {
      logger.debug('Journey', 'getFeedback not found', { journeyId });
      return null;
    }
  }

  async assignPackage(journeyId: string, packageId: string): Promise<Journey> {
    logger.info('Journey', 'assignPackage', { journeyId, packageId });
    const raw = await api.patch<ApiJourney>(`/api/journeys/${journeyId}`, {
      package_id: packageId,
    });
    return toJourney(raw);
  }

  async generateJourneys(userId: string, count?: number): Promise<Journey[]> {
    const body: Record<string, unknown> = { user_id: userId };
    if (count !== undefined) body.count = count;

    logger.info('Journey', 'generateJourneys', { userId, count });

    // AGI Intelligence Layer §2: backend response is
    //   { journeys: ApiJourney[], source: 'ai' | 'template' }
    // Older deployments returned a bare ApiJourney[] — handle both shapes so
    // we tag each journey with `source` for the "AI Curated" badge.
    const raw = await api.post<
      ApiJourney[] | { journeys: ApiJourney[]; source?: 'ai' | 'template' }
    >('/api/journeys/generate', body);

    if (Array.isArray(raw)) {
      logger.info('Journey', 'generateJourneys done (legacy shape)', {
        count: raw.length,
      });
      return raw.map((j) => toJourney(j));
    }

    const source = raw?.source;
    const journeys = raw?.journeys ?? [];
    logger.info('Journey', 'generateJourneys done', {
      count: journeys.length,
      source,
    });
    return journeys.map((j) => toJourney(j, source));
  }
}
