/**
 * Journey Service Interface
 * Manages journey creation, versioning, and lifecycle
 */

import {
  Journey,
  JourneyVersion,
  CreateJourneyInput,
  DomainContext,
  PreDepartureBrief,
  JourneyFeedback,
  TravelMonitor,
} from '@/lib/types';

export interface IJourneyService {
  getJourneys(userId: string, context: DomainContext): Promise<Journey[]>;
  getJourneyById(id: string): Promise<Journey | null>;
  createJourney(data: CreateJourneyInput): Promise<Journey>;
  updateJourney(id: string, data: Partial<Journey>): Promise<Journey>;
  deleteJourney(id: string): Promise<boolean>;
  getJourneyVersions(journeyId: string): Promise<JourneyVersion[]>;
  createJourneyVersion(journeyId: string, data: Partial<JourneyVersion>): Promise<JourneyVersion>;
  /** Execute a state-machine transition (e.g. SUBMIT_FOR_REVIEW, APPROVE_RM, SUBMIT_FEEDBACK) */
  transitionJourney(journeyId: string, event: string, rejectionReason?: string): Promise<Journey>;
  /** AI-powered journey generation via backend */
  generateJourneys(userId: string, count?: number): Promise<Journey[]>;

  /**
   * Phase 4 §6 — Advisor composes pre-departure brief.
   * Only the composer-facing subset is accepted; id / journeyId / createdAt /
   * createdBy are set server-side.
   */
  setPreDepartureBrief(
    journeyId: string,
    brief: Pick<PreDepartureBrief, 'summary' | 'logistics' | 'advisorNotes' | 'autoGenerated'>
  ): Promise<Journey>;
  /** Phase 4 §7 — Advisor travel monitor for EXECUTED journeys */
  getMonitor(journeyId: string): Promise<TravelMonitor>;
  /** Phase 4 §4 — UHNI submits post-journey feedback (mood + reflection + emotional_tags) */
  submitFeedback(
    journeyId: string,
    feedback: { mood: number; reflection?: string; emotional_tags?: string[] }
  ): Promise<JourneyFeedback>;
  /** Phase 4 §4 — Fetch existing feedback for a journey (null if none) */
  getFeedback(journeyId: string): Promise<JourneyFeedback | null>;
  /** Phase 4 §5 — Assign an experience package to a journey */
  assignPackage(journeyId: string, packageId: string): Promise<Journey>;
}
