/**
 * Journey Service Interface
 * Manages journey creation, versioning, and lifecycle
 */

import { Journey, JourneyVersion, JourneyFeedback, PreDepartureBrief, TravelMonitor, CreateJourneyInput, DomainContext } from '@/lib/types';

export interface IJourneyService {
  getJourneys(userId: string, context: DomainContext): Promise<Journey[]>;
  getJourneyById(id: string): Promise<Journey | null>;
  createJourney(data: CreateJourneyInput): Promise<Journey>;
  updateJourney(id: string, data: Partial<Journey>): Promise<Journey>;
  deleteJourney(id: string): Promise<boolean>;
  getJourneyVersions(journeyId: string): Promise<JourneyVersion[]>;
  createJourneyVersion(journeyId: string, data: Partial<JourneyVersion>): Promise<JourneyVersion>;
  /** Execute a state-machine transition (e.g. SUBMIT_FOR_REVIEW, APPROVE_RM) */
  transitionJourney(journeyId: string, event: string, rejectionReason?: string): Promise<Journey>;
  /** AI-powered journey generation via backend */
  generateJourneys(userId: string, count?: number): Promise<Journey[]>;
  /** Submit post-journey emotional feedback */
  submitFeedback(journeyId: string, data: { mood: number; reflection?: string; emotionalTags?: string[] }): Promise<JourneyFeedback>;
  /** Get feedback for a journey */
  getFeedback(journeyId: string): Promise<JourneyFeedback[]>;
  /** Set pre-departure brief for a journey */
  setPreDepartureBrief(journeyId: string, data: { summary: string; logistics?: Record<string, unknown>; advisorNotes?: string; autoGenerated?: boolean }): Promise<PreDepartureBrief>;
  /** Get live travel monitor data */
  getTravelMonitor(journeyId: string): Promise<TravelMonitor | null>;
}
